name: Rebase Upstream
on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10  # greater than the number of commits you made
        token: ${{ secrets.GH_PAT }}
    - uses: imba-tjd/rebase-upstream-action@master
      with:
        token: ${{ secrets.GH_PAT }}
